In [89]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [90]:
customers=pd.read_csv('/Users/varunchirunagula/Downloads/olist_customers_dataset.csv')
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [91]:
orders=pd.read_csv('/Users/varunchirunagula/Downloads/olist_orders_dataset.csv')
order_items=pd.read_csv('//Users/varunchirunagula/Downloads/olist_order_items_dataset.csv')
payments=pd.read_csv('/Users/varunchirunagula/Downloads/olist_order_payments_dataset.csv')
products=pd.read_csv('/Users/varunchirunagula/Downloads/olist_products_dataset.csv')

In [92]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [93]:
payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [94]:
order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [95]:
df = orders.merge(customers, on='customer_id') \
           .merge(order_items, on='order_id') \
           .merge(payments, on='order_id') \
           .merge(products, on='product_id')

In [96]:
df.shape

(117601, 30)

In [97]:
df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,payment_installments,payment_value,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,1,18.12,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,1,2.00,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,1,18.59,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,af07308b275d755c9edb36a90c618231,47813,...,1,141.46,perfumaria,29.0,178.0,1.0,400.0,19.0,13.0,19.0
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,3a653a41f6f9fc3d2a113cf8398680e8,75265,...,3,179.12,automotivo,46.0,232.0,1.0,420.0,24.0,19.0,21.0

In [98]:
orders.shape

(99441, 8)

In [99]:
df.is_null().sum()

AttributeError: 'DataFrame' object has no attribute 'is_null'

In [ ]:
df.describe()

,customer_zip_code_prefix,order_item_id,price,freight_value,payment_sequential,payment_installments,payment_value,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
count,117601.000000,117601.000000,117601.000000,117601.000000,117601.000000,117601.000000,117601.000000,115903.000000,115903.000000,115903.000000,117581.000000,117581.000000,117581.000000,117581.000000
mean,35051.793097,1.195900,120.824783,20.045990,1.093528,2.939482,172.686752,48.767590,786.950855,2.207881,2114.309497,30.257235,16.630306,23.068574
std,29820.588877,0.697706,184.479323,15.861315,0.726692,2.774223,267.592290,10.035011,653.036231,1.719531,3788.798201,16.190920,13.458952,11.748468
min,1003.000000,1.000000,0.850000,0.000000,1.000000,0.000000,0.000000,5.000000,4.000000,1.000000,0.000000,7.000000,2.000000,6.000000
25%,11310.000000,1.000000,39.900000,13.080000,1.000000,1.000000,60.870000,42.000000,347.000000,1.000000,300.000000,18.000000,8.000000,15.000000
50%,24315.000000,1.000000,74.900000,16.290000,1.000000,2.000000,108.210000,52.000000,601.000000,1.000000,700.000000,25.000000,13.000000,20.000000
75%,58600.000000,1.000000,134.900000,21.190000,1.000000,4.000000,189.260000,57.000000,985.000000,3.000000,1800.000000,38.000000,20.000000,30.000000
max,99990.000000,21.000000,6735.000000,409.680000,29.000000,24.000000,13664.080000,76.000000,3992.000000,20.000000,40425.000000,105.000000,105.000000,118.000000

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 117601 entries, 0 to 117600
Data columns (total 30 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       117601 non-null  str
 1   customer_id                    117601 non-null  str
 2   order_status                   117601 non-null  str
 3   order_purchase_timestamp       117601 non-null  str
 4   order_approved_at              117586 non-null  str
 5   order_delivered_carrier_date   116356 non-null  str
 6   order_delivered_customer_date  115034 non-null  str
 7   order_estimated_delivery_date  117601 non-null  str
 8   customer_unique_id             117601 non-null  str
 9   customer_zip_code_prefix       117601 non-null  int64
 10  customer_city                  117601 non-null  str
 11  customer_state                 117601 non-null  str
 12  order_item_id                  117601 non-null  int64
 13  product_id                     117601 non-null  str
 14  seller_id                      117601 non-null  str
 15  shipping_limit_date            117601 non-null  str
 16  price                          117601 non-null  float64
 17  freight_value                  117601 non-null  float64
 18  payment_sequential             117601 non-null  int64
 19  payment_type                   117601 non-null  str
 20  payment_installments           117601 non-null  int64
 21  payment_value                  117601 non-null  float64
 22  product_category_name          115903 non-null  str
 23  product_name_lenght            115903 non-null  float64
 24  product_description_lenght     115903 non-null  float64
 25  product_photos_qty             115903 non-null  float64
 26  product_weight_g               117581 non-null  float64
 27  product_length_cm              117581 non-null  float64
 28  product_height_cm              117581 non-null  float64
 29  product_width_cm               117581 non-null  float64
dtypes: float64(10), int64(4), str(16)
memory usage: 26.9 MB

In [ ]:
df.isnull()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,payment_installments,payment_value,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117596,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
117597,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
117598,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
117599,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
117600,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                  15
order_delivered_carrier_date     1245
order_delivered_customer_date    2567
order_estimated_delivery_date       0
customer_unique_id                  0
customer_zip_code_prefix            0
customer_city                       0
customer_state                      0
order_item_id                       0
product_id                          0
seller_id                           0
shipping_limit_date                 0
price                               0
freight_value                       0
payment_sequential                  0
payment_type                        0
payment_installments                0
payment_value                       0
product_category_name            1698
product_name_lenght              1698
product_description_lenght       1698
product_photos_qty               1698
product_weight_g                   20
product_length_cm                  20
product_height_cm                  20
product_width_cm                   20
dtype: int64

In [ ]:
df.isnull().sum().sum()

np.int64(10699)

In [ ]:
df.fillna('Unkown')

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,payment_installments,payment_value,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,1,18.12,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,1,2.00,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,1,18.59,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,af07308b275d755c9edb36a90c618231,47813,...,1,141.46,perfumaria,29.0,178.0,1.0,400.0,19.0,13.0,19.0
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,3a653a41f6f9fc3d2a113cf8398680e8,75265,...,3,179.12,automotivo,46.0,232.0,1.0,420.0,24.0,19.0,21.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117596,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00,da62f9e57a76d978d02ab5362c509660,11722,...,3,195.00,bebes,52.0,828.0,4.0,4950.0,40.0,10.0,40.0
117597,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00,737520a9aad80b3fbbdad19b66b37b30,45920,...,5,271.01,eletrodomesticos_2,51.0,500.0,2.0,13300.0,32.0,90.0,22.0
117598,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00,5097a5312c8b157bb7be58ae360ef43c,28685,...,4,441.16,informatica_acessorios,59.0,1893.0,1.0,6550.0,20.0,20.0,20.0
117599,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00,5097a5312c8b157bb7be58ae360ef43c,28685,...,4,441.16,informatica_acessorios,59.0,1893.0,1.0,6550.0,20.0,20.0,20.0
117600,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00,60350aa974b26ff12caad89e55993bd6,83750,...,1,86.86,beleza_saude,45.0,569.0,1.0,150.0,16.0,7.0,15.0

In [ ]:
df.isnull().sum().sum()

np.int64(5174)

In [ ]:
df.isnull()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,payment_installments,payment_value,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117596,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
117597,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
117598,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
117599,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
117600,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.isnull().sum().sum()

np.int64(5174)

In [ ]:
df.fillna(0)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,payment_installments,payment_value,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,1,18.12,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,1,2.00,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,1,18.59,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,af07308b275d755c9edb36a90c618231,47813,...,1,141.46,perfumaria,29.0,178.0,1.0,400.0,19.0,13.0,19.0
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,3a653a41f6f9fc3d2a113cf8398680e8,75265,...,3,179.12,automotivo,46.0,232.0,1.0,420.0,24.0,19.0,21.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117596,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00,da62f9e57a76d978d02ab5362c509660,11722,...,3,195.00,bebes,52.0,828.0,4.0,4950.0,40.0,10.0,40.0
117597,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00,737520a9aad80b3fbbdad19b66b37b30,45920,...,5,271.01,eletrodomesticos_2,51.0,500.0,2.0,13300.0,32.0,90.0,22.0
117598,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00,5097a5312c8b157bb7be58ae360ef43c,28685,...,4,441.16,informatica_acessorios,59.0,1893.0,1.0,6550.0,20.0,20.0,20.0
117599,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00,5097a5312c8b157bb7be58ae360ef43c,28685,...,4,441.16,informatica_acessorios,59.0,1893.0,1.0,6550.0,20.0,20.0,20.0
117600,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00,60350aa974b26ff12caad89e55993bd6,83750,...,1,86.86,beleza_saude,45.0,569.0,1.0,150.0,16.0,7.0,15.0

In [ ]:
df.isnull()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,payment_installments,payment_value,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117596,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
117597,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
117598,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
117599,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
117600,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
df['total_price'] = df['price'] + df['freight_value']

df['order_purchase_timestamp'] = pd.to_datetime(df['order_purchase_timestamp'])

df['year'] = df['order_purchase_timestamp'].dt.year
df['month'] = df['order_purchase_timestamp'].dt.month

In [ ]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [119]:
df['total_price']=df['price']+df['freight_value']

In [ ]:
df['order_purchase_timestamp']=pd.to_datetime(df['order_purchase_timestamp'])

In [ ]:
df['year']=df['order_purchase_timestamp'].dt.year
df['month']=df['order_purchase_timestamp'].dt.month

In [120]:
clv=df.groupby('customer_unique_id')['total_price'].sum().reset_index()
clv.columns = ['customer_id', 'lifetime_value']

In [114]:
frequency=df.groupby('customer_unique_id')['order_id'].nunique().reset_index()
frequency.columns = ['customer_id', 'frequency']
frequency

                            customer_id  frequency
0      0000366f3b9a7992bf8c76cfdf3221e2          1
1      0000b849f77a49e4a4ce2b2a4ca5be3f          1
2      0000f46a3911fa3c0805444483337064          1
3      0000f6ccb0745a6a4b88665a16c9f078          1
4      0004aac84e0df4da2b147fca70cf8255          1
...                                 ...        ...
95414  fffcf5a5ff07b0908bd4e2dbc735a684          1
95415  fffea47cd6d3cc0a88bd621562a9d061          1
95416  ffff371b4d645b6ecea244b27531430a          1
95417  ffff5962728ec6157033ef9805bacc48          1
95418  ffffd2657e2aad2907e67c3e9daecbeb          1

[95419 rows x 2 columns]

In [ ]:
clv

customer_unique_id
0000366f3b9a7992bf8c76cfdf3221e2     141.90
0000b849f77a49e4a4ce2b2a4ca5be3f      27.19
0000f46a3911fa3c0805444483337064      86.22
0000f6ccb0745a6a4b88665a16c9f078      43.62
0004aac84e0df4da2b147fca70cf8255     196.89
                                     ...
fffcf5a5ff07b0908bd4e2dbc735a684    2067.42
fffea47cd6d3cc0a88bd621562a9d061      84.58
ffff371b4d645b6ecea244b27531430a     112.46
ffff5962728ec6157033ef9805bacc48     133.69
ffffd2657e2aad2907e67c3e9daecbeb      71.56
Name: total_price, Length: 95419, dtype: float64

In [ ]:
customer_data = clv.merge(frequency, on='customer_id')
customer_data

                            customer_id  lifetime_value  frequency
0      0000366f3b9a7992bf8c76cfdf3221e2          141.90          1
1      0000b849f77a49e4a4ce2b2a4ca5be3f           27.19          1
2      0000f46a3911fa3c0805444483337064           86.22          1
3      0000f6ccb0745a6a4b88665a16c9f078           43.62          1
4      0004aac84e0df4da2b147fca70cf8255          196.89          1
...                                 ...             ...        ...
95414  fffcf5a5ff07b0908bd4e2dbc735a684         2067.42          1
95415  fffea47cd6d3cc0a88bd621562a9d061           84.58          1
95416  ffff371b4d645b6ecea244b27531430a          112.46          1
95417  ffff5962728ec6157033ef9805bacc48          133.69          1
95418  ffffd2657e2aad2907e67c3e9daecbeb           71.56          1

[95419 rows x 3 columns]

In [ ]:
def segment(x):
    if x > 1000:
        return 'High Value'
    elif x >= 300:
        return 'Medium Value'
    else:
        return 'Low Value'

In [126]:
monthly_sales = df.groupby(['year','month'])['total_price'].sum().reset_index()
monthly_sales

KeyError: 'year'

In [128]:
category_sales = df.groupby('product_category_name')['total_price'].sum().reset_index()
category_sales

        product_category_name  total_price
0   agro_industria_e_comercio     90808.77
1                   alimentos     37649.99
2           alimentos_bebidas     21091.48
3                       artes     28912.99
4          artes_e_artesanato      2184.14
..                        ...          ...
68    sinalizacao_e_seguranca     28120.83
69   tablets_impressao_imagem      9140.68
70                  telefonia    413564.32
71             telefonia_fixa     66465.41
72      utilidades_domesticas    820851.24

[73 rows x 2 columns]

In [130]:
location_sales = df.groupby('customer_city')['total_price'].sum().reset_index()
location_sales

            customer_city  total_price
0     abadia dos dourados       413.50
1               abadiania      1025.52
2                  abaete      1946.81
3              abaetetuba      4739.21
4                 abaiara       332.15
...                   ...          ...
4105             xinguara      1608.51
4106          xique-xique       230.56
4107             zacarias       229.85
4108              ze doca       878.92
4109               zortea       137.57

[4110 rows x 2 columns]

In [110]:
customer_data.to_csv("customer_segmentation.csv", index=False)
monthly_sales.to_csv("monthly_sales.csv", index=False)
category_sales.to_csv("category_sales.csv", index=False)
location_sales.to_csv("location_sales.csv", index=False)

In [109]:
monthly_sales.head()

   year  month  total_price
0  2016      9       211.29
1  2016     10     58550.03
2  2016     12        19.62
3  2017      1    146455.54
4  2017      2    302230.37

In [111]:
monthly_sales.to_csv("monthly_sales.csv", index=False)

In [112]:
monthly_sales.head()

   year  month  total_price
0  2016      9       211.29
1  2016     10     58550.03
2  2016     12        19.62
3  2017      1    146455.54
4  2017      2    302230.37

In [118]:
df.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'customer_unique_id', 'customer_zip_code_prefix', 'customer_city',
       'customer_state', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value', 'payment_sequential',
       'payment_type', 'payment_installments', 'payment_value',
       'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm'],
      dtype='str')

In [129]:
category_sales.to_csv("category_sales.csv", index=False)

In [131]:
location_sales.to_csv("location_sales.csv", index=False)